# Tweet's langage. 'fr' for French 'en' for English...
lang : 'fr'

# Trends on twitter by region, you can find the woeid on http://www.woeidlookup.com/
# Exemple : France is 23424819
woeid : 23424819

# Needed retweet number to like and retweet a tweet
nbRtLikeRt : 5

# Needed retweet number to follow an account
nbRtFollow : 500

# Maximum number of month (compared to the current date) the tweet mustn't exceed to be processed
monthMax : 1
