# Tweet's langage. 'fr' for French 'en' for English...
lang : 'fr'

# Trends on twitter by region, you can find the woeid on http://www.woeidlookup.com/
# Exemple : France is 23424819
woeid : 23424819

# Number of retweet nedded to retweet a tweet for the -m (hashtag) mod
nb_rt_hashtag : 5

# Number of retweet needed to play to a contest for the -c (contest) mod
nb_rt_contest : 500

# Maximum number of month (compared to the current date) the tweet mustn't exceed to be processed
monthMax : 1
